name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install -r bin/requirements.txt
    - run: make --always-make
    - uses: actions/upload-artifact@v3
      with:
        name: chess-openings
        path: dist/
